#+title: About
#+author: Preston Pan
#+description: About me and my contact information
#+html_head: <link rel="stylesheet" type="text/css" href="style.css" />
#+language: en
#+OPTIONS: broken-links:t
#+date: <2023-06-26 Mon>
#+html_head: <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
#+html_head: <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
#+html_head: <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
#+html_head: <link rel="manifest" href="/site.webmanifest">
#+html_head: <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
#+html_head: <meta name="msapplication-TileColor" content="#da532c">
#+html_head: <meta name="theme-color" content="#ffffff">

* Webrings
This website is a part of these webrings:

[[https://baccyflap.com][<]] [[https://nullring.xyz][nullring]] [[https://pen15.agency][>]]

* About Me
** whoami?
[[https://preston.nullring.xyz][Preston Pan]]. Although, that is not really important for the enjoyment of ret2pop, and
it is certainly not the focus at all. Ret2pop is a separate entity, controlled only
by the will of Francois. Ret2pop is a relentlessly curious force willing to entertain
ideas that are unconventional and unorthodox; Preston Pan is the individual that tries
to live this out and fails in a somewhat cringy manner.

Some might know me as ret2pop, some as Preston Pan, and others as LiCoO2.
** Contact
Here are all the methods you should use to contact me:
*** IRC
- ret2pop on libera.chat
  - Note: I will not always be online and I don't use a bouncer on this server. Email me to coordinate a time if you really need to reach me this way.
*** Email
- preston@nullring.xyz
- ret2pop@gmail.com
*** Amateur Radio (In case the world ends)
My callsign is ~VE7PPN~.
*** Linkedin
You can see my [[https://ca.linkedin.com/in/preston-pan-4aa635296][personal linkedin profile]].

* Professional
Here you can find [[file:./resume2.pdf][my resume]], which contains it all. I am always open for new job opportunities!

* How Old am I?
born in 12/23/2005, but does it really matter?
