#+title: ret2pop
#+author: Preston Pan
#+date: <2023-06-11 Sun>
#+description: My website for all things.
#+html_head: <link rel="stylesheet" type="text/css" href="style.css" />

* What is this?
It's ret2pop! My website for all things math. Wait, no. Computer science.
Music. Okay, let me try that again.

It's ret2pop! My website for all things.

** Sounds awesome! But why is it written in org instead of html?
Because I have converted to the church of emacs. Remember:
anything and everything that can be rewritten in org, can and should
be rewritten in org.
*** so how did you actually do that?
By using the ~org-publish~ function, ~org-roam~, and ~org-journal~,
as well as writing a lot of things with a literate config.
** So, where is this website of yours located?
https://ret2pop.nullring.xyz, it is the road to enlightenment.

* Wait, so where are your dotfiles?
To use my dotfiles, clone this repository:
#+begin_src bash
git clone https://github.com/ret2pop/ret2pop-website.git ~/org/website
#+end_src
and install my [[https://github.com/ret2pop/hyprnixmacs][NixOS Configuration]]. The org files /are/ the dotfiles, or
at least in the case of emacs.

To use my full system, you also need to have a ~password-store~ from the ~pass~
password manager in its standard location with an entry called ~Mail~, and you need
to clone my [[https://github.com/ret2pop/wallpapers.git][wallpapers]] repository.

* License
See the [[file:LICENSE.org][license]]. The style.css has its own license.
