#+title: ret2pop
#+author: Preston Pan
#+date: <2023-06-11 Sun>
#+description: My website for all things.
#+html_head: <link rel="stylesheet" type="text/css" href="style.css" />

* What is this?
It's ret2pop! My website for all things math. Wait, no. Computer science.
Music. Okay, let me try that again.

It's ret2pop! My website for all things.

** Sounds awesome! But why is it written in org instead of html?
Because I have converted to the church of emacs. Remember:
anything and everything that can be rewritten in org, can and should
be rewritten in org.
*** so how did you actually do that?
By using the ~org-publish~ function, ~org-roam~, and ~org-journal~,
as well as writing a lot of things with a literate config.
** So, where is this website of yours located?
https://ret2pop.nullring.xyz, it is the road to enlightenment.

* Wait, so where are your dotfiles?
To use my dotfiles, clone this repository:
#+begin_src bash
git clone https://github.com/ret2pop/ret2pop-website.git ~/org/website
#+end_src
and install my ~configuration.nix~ file. The org files /are/ the dotfiles, or
at least in the case of emacs.

To use my full system, you also need to have a ~password-store~ from the ~pass~
password manager in its standard location with an entry called ~Mail~, and you need
to clone my [[https://github.com/ret2pop/wallpapers.git][wallpapers]] repository. Therefore, in full, my configuration can be fully
installed like so:
#+begin_src bash
  # Run this in root, and after copying the configuration.nix file and running nixos-rebuild switch.
  # You must also change the gpg key used for git and pass. Make sure
  # you've installed your gpg keys and your ssh keys before this.
  # Install your music to ~/music. Of course, also change your location
  # of stuff like your mail server.
  su preston # if you change your username, change this too
  cd ~
  mkdir ~/org
  # if you want to make this process deterministic, clone a particular commit
  git clone https://github.com/ret2pop/ret2pop-website.git ~/org/website
  git clone https://github.com/ret2pop/wallpapers.git
  # replace this with your password-store
  git clone git@nullring.xyz:/var/www/password_store.git ~/.password-store/
  mbsync prestonpan # change this with your own name in the nix config and here
  # TODO: mu init/index
  mpc add /

  # Afterwards, open firefox, enable all the plugins that are already installed,
  # and install the catppuccin firefox theme. For vencord, use the catppuccin
  # betterdiscord theme; open emacs and run pdf-tools-install, nerd-icons-install-fonts,
  # and all-the-icons-install-fonts. These things are not completely set up for you but
  # the good news is that the vast majority of the functionality is included.

#+end_src
Without the comments, it is a 10 line program that installs everything needed to run my system,
and configures those programs as well!
* License
See the [[file:LICENSE.org][license]]. The style.css has its own license.
