:PROPERTIES:
:ID:       ece8bf94-4e3c-4939-a77a-9949c1ec0dc6
:END:
#+title: physics
#+author: Preston Pan
#+html_head: <link rel="stylesheet" type="text/css" href="../style.css" />
#+html_head: <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
#+html_head: <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
#+options: broken-links:t

* Laws of Nature
By engaging in physics modeling, we are postulating that there are rules that
"nature" follows, and that these rules are logically consistent. At least,
mathematical models postulate this, and non-mathematical models of the universe
have been relegated to the study of metaphysics.

* Fields in Physics
The current challenge in physics is uniting the big and the small; general relativity, and quantum mechanics.
There is no currently known theory that can describe [[id:2b8515d8-9f3c-44a3-a40d-147f6a2bbb25][everything]], and the very nature of this problem is one containing
many correspondences and [[id:1b1a8cff-1d20-4689-8466-ea88411007d7][dualities]].
** Classical Mechanics
Classical mechanics deals with fields of physics that do not deal with time dilation or quantum
weirdness. It is called classical mechanics because most of these theories were invented before
their quantum or relativistic counterparts, and usually serve as a baseline understanding
for the later topics.
*** [[id:6e2a9d7b-7010-41da-bd41-f5b2dba576d3][Newtonian mechanics]]
It all started when Newton created three (but really two) fundamental laws of the universe that
governed all things.
*** [[id:83da205c-7966-417e-9b77-a0a354099f30][Lagrangian mechanics]]
This is a different strain of classical mechanics. Instead of looking at direction and vectors,
it looks at a single fundamental principle, even more fundamental than inertia and conservation of momentum:
optimization. We believe that nature always optimizes for some parameters in all physical phenomena. Almost
all physical theories including electromagnetism, general relativity, Newtonian mechanics, and even quantum
mechanics can be explained within the Lagrangian framework.
*** Fluid Mechanics
*** Thermodynamics
*** Classical Electrodynamics
Classical electrodynamics attempts to explain the electromagnetic force from a classical perspective. What is
light? How does electricity actually work? All these questions you will find (half) answered in the study
of electrodynamics, giving rise to the complete theory encoded in [[id:fde2f257-fa2e-469a-bc20-4d11714a515e][Maxwell's Equations]].
*** General Relativity
General Relativity aims unify gravity with [[id:e38d94f2-8332-4811-b7bd-060f80fcfa9b][special relativity]], in a unified theory of macroscopic forces
including classical electromagnetism.
** [[id:136e79df-106f-4989-ab19-89705929cf91][Quantum Mechanics]] 
Quantum mechanics renounces all hope of having a deterministic view of physics, and instead replaces direct causation
with statistical causation, at least according to some interpretations.
** QFT
Quantum Field Theory is an approach that combines [[id:e38d94f2-8332-4811-b7bd-060f80fcfa9b][special relativity]] with [[id:136e79df-106f-4989-ab19-89705929cf91][quantum mechanics]], then utilizing a process
called canonical quantization in order to quantize a given field. This is the closest thing we have to a theory of [[id:2b8515d8-9f3c-44a3-a40d-147f6a2bbb25][everything]]
in physics.

* Note
I did not exhaustively cover all fields in physics but this is most of it.
